### PR TITLE
MILESTONE: Application Deployment.

### PR DESCRIPTION
**Pull request by joramot**
- Create on GitHub page site for the project.
- Add LICENSE file.
- Update README file.
- Update the title in the index.html

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @joramot, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project, that doesn't have a pull request description, kindly add one. See a demo on how to add a PR description below:

pull_request_desc
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by joramot** [comment]
Do application deploy.

- Add LICENSE file
- Update README file.
- Update title in the index.html

**Comment by huseyinbiyik** [comment]
Hi @joramot,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

⚠️ Please fix your pull request description to make your repository more professional. Kindly check the gif I made for you below.
Screen Recording 2023-01-30 at 10 53 00 PM


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by nahnahdev — COMMENTED** [review]
Hi @joramot , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that is missing some sections of the Microverse Readme Template. In the screenshot below, you can see that the Future Features section in your project comes after the Authors section but you're currently missing that section. :wink: Please ensure that you add at least one Future Feature to your README file :100: 

image


- [ ]  Kindly remove the Microverse logo. If you have your own logo, you can use it but I would advise you to remove it. You can remove the entire `<div>` tag wrapped around the logo. :100: 

- [ ] Please ensure that the link to your MIT license file in your project is working properly. It is included in your README file but it's broken so kindly fix the link :wink:. The MIT License is a popular open-source license that allows others to use, modify, and distribute your code as long as they give credit to you the original author, and include the original license text. You can use this link to learn how to add one to your project :100: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
